- topic: ML.MQ
  queueName: fib
  bindingKey: "predict.*"
  replyTo: "response"
  argQueue: {
    "x-dead-letter-exchange": dead_letter_exchange,
  }
- topic: ML.MQ
  queueName: manage
  bindingKey: "metrics.*"
  replyTo: "response"
